//! Signup

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

//! Login

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

//! Logout

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

//! User Reducer

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const FETCH_USER_DATA_REQUEST = "FETCH_USER_DATA_REQUEST";
export const SET_USER_DATA = "SET_USER_DATA";
export const FETCH_USER_DATA_FAILED = "FETCH_USER_DATA_FAILED";

//! UI Reducer

export const LOADING_UI = "LOADING_UI";
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//! Data Reducer

export const SCREAMS_REQUEST = "SCREAM_REQUEST";
export const SET_SCREAM = "SET_SCREAM";
export const SET_SCREAMS = "SET_SCREAMS";
export const SCREAMS_FAILED = "SCREAM_FAILED";

export const LIKE_SCREAM = "LIKE_SCREAM";
export const UNLIKE_SCREAM = "UNLIKE_SCREAM";
export const LIKEUNLIKE_REQUEST = "LIKEUNLIKE_REQUEST";
export const LIKEUNLIKE_FAILED = "LIKEUNLIKE_FAILED";

export const POST_SCREAM_STATRT = "POST_SCREAM_STATRT";
export const POST_SCREAM_SUCCESSS = "POST_SCREAM_SUCCESS";
export const POST_SCREAM_FAILED = "POST_SCREAM_FAILED";

export const DELETE_SCREAM_SUCCESS = "DELETE_SCREAM_SUCCESS";

//! Email Verification

export const VERIFY_START = "VERIFY_START";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAILED = "VERIFY_FAILED";

//! Recover Password

export const RECOVERY_START = "RECOVERY_START";
export const RECOVERY_SUCCESS = "RECOVERY_SUCCESS";
export const RECOVERY_FAILED = "RECOVERY_FAILED";
